apiVersion: 1

datasources:
  - name: FraudMetrics
    type: postgres
    url: postgres:5432
    database: fraud_monitoring
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
    editable: false
